<template>
  <aside class="app-card flex min-h-0 flex-col overflow-hidden xl:sticky xl:top-24 xl:max-h-[calc(100vh-8rem)]">
    <header class="bg-slate-950 p-5 text-white"><div class="flex items-start justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-[0.14em] text-cyan-300">Venta actual</p><h2 class="mt-1 text-xl font-black tracking-tight">Carrito de cobro</h2></div><span class="grid h-9 min-w-9 place-items-center rounded-xl bg-white/10 px-2 text-sm font-bold text-cyan-100">{{ cart.length }}</span></div><p class="mt-2 text-xs text-slate-400">Revisa los productos antes de completar.</p></header>
    <div class="border-b border-slate-100 bg-slate-50/70 p-4"><p class="mb-2 text-[11px] font-bold uppercase tracking-wider text-slate-500">Cliente</p><form class="flex gap-2" @submit.prevent="$emit('find-customer')"><input :value="documentNumber" class="field-control min-w-0 !rounded-xl !py-2.5 text-xs" placeholder="DNI o RUC (opcional)" @input="$emit('update:document-number', $event.target.value)" /><button class="btn btn-secondary !rounded-xl px-3 py-2 text-xs" type="submit"><Search :size="16" /><span class="hidden sm:inline">Consultar</span></button></form><p v-if="customer" class="mt-2 rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800">Cliente: {{ customer.nombre_razon_social || customer.nombre }}</p></div>
    <div class="min-h-48 flex-1 overflow-y-auto p-4"><ul v-if="cart.length" class="space-y-3"><li v-for="(item, index) in cart" :key="item.producto_id" class="rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm"><div class="flex justify-between gap-3"><div class="min-w-0"><p class="line-clamp-2 text-sm font-black text-slate-900">{{ item.nombre }}</p><p v-if="item.requiere_receta" class="mt-1 text-[11px] font-bold text-red-700">CMP: {{ item.cmp_medico || 'Pendiente' }}</p></div><button class="rounded-lg p-1 text-slate-400 hover:bg-red-50 hover:text-red-600" :aria-label="'Quitar ' + item.nombre" @click="$emit('remove', index)"><Trash2 :size="17" /></button></div><div class="mt-3 flex items-center justify-between"><div class="flex items-center rounded-xl border border-slate-200 bg-slate-50"><button class="p-1.5 text-slate-500 hover:bg-white" aria-label="Reducir cantidad" @click="$emit('quantity', item, item.cantidad - 1)"><Minus :size="15" /></button><input class="w-9 border-x border-slate-200 bg-white py-1.5 text-center text-xs font-black outline-none" :value="item.cantidad" min="1" type="number" @change="$emit('quantity', item, Number($event.target.value))" /><button class="p-1.5 text-slate-500 hover:bg-white" aria-label="Aumentar cantidad" @click="$emit('quantity', item, item.cantidad + 1)"><Plus :size="15" /></button></div><strong class="text-sm font-black text-slate-900">S/ {{ money(item.cantidad * item.precio_unitario) }}</strong></div></li></ul><div v-else class="grid h-full min-h-52 place-items-center rounded-2xl border border-dashed border-slate-200 bg-slate-50/60 p-6 text-center"><div><span class="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-white text-cyan-700 shadow-sm"><ShoppingBasket :size="24" /></span><p class="mt-4 font-black text-slate-800">El carrito espera productos</p><p class="mt-1 text-sm leading-5 text-slate-500">Selecciona uno del catálogo para iniciar la venta.</p></div></div></div>
    <footer class="border-t border-slate-100 bg-white p-4"><label class="field-label">Método de pago</label><select :value="paymentMethod" class="field-control !rounded-xl py-2.5" @change="$emit('update:payment-method', $event.target.value)"><option value="Efectivo">Efectivo</option><option value="Yape">Yape</option><option value="Plin">Plin</option><option value="Tarjeta">Tarjeta de débito/crédito</option></select><div class="my-4 rounded-2xl bg-gradient-to-br from-slate-950 to-slate-800 p-4 text-white shadow-lg shadow-slate-900/10"><div class="flex items-end justify-between"><span class="text-sm font-medium text-slate-300">Total a pagar</span><strong class="text-3xl font-black tracking-tight">S/ {{ money(total) }}</strong></div><p class="mt-1 text-[11px] text-slate-400">Incluye los productos seleccionados.</p></div><button class="btn w-full !rounded-2xl bg-emerald-600 py-3 text-white shadow-lg shadow-emerald-600/20 hover:bg-emerald-700" :disabled="!cart.length || processing" @click="$emit('checkout')"><LoaderCircle v-if="processing" class="animate-spin" :size="18" /><CreditCard v-else :size="18" />{{ processing ? 'Procesando venta…' : 'Completar venta' }}</button></footer>
  </aside>
</template>
<script setup>
import { CreditCard, LoaderCircle, Minus, Plus, Search, ShoppingBasket, Trash2 } from 'lucide-vue-next';
defineProps({ cart: { type: Array, default: () => [] }, customer: Object, documentNumber: { type: String, default: '' }, paymentMethod: { type: String, default: 'Efectivo' }, processing: Boolean, total: { type: Number, default: 0 } });
defineEmits(['update:document-number', 'find-customer', 'remove', 'quantity', 'update:payment-method', 'checkout']);
const money = (value) => Number(value || 0).toFixed(2);
</script>
