<template>
  <aside class="app-card flex min-h-0 flex-col overflow-hidden">
    <header class="border-b border-slate-100 p-4 sm:p-5"><p class="text-xs font-semibold uppercase tracking-wider text-cyan-700">Venta actual</p><h2 class="mt-1 text-lg font-bold text-slate-900">Detalle de venta</h2></header>
    <div class="border-b border-slate-100 p-4"><form class="flex gap-2" @submit.prevent="$emit('find-customer')"><input :value="documentNumber" class="field-control min-w-0 py-2 text-xs" placeholder="DNI o RUC (opcional)" @input="$emit('update:document-number', $event.target.value)" /><button class="btn btn-secondary px-3 py-2 text-xs" type="submit"><Search :size="16" /><span class="hidden sm:inline">Consultar</span></button></form><p v-if="customer" class="mt-2 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-800">Cliente: {{ customer.nombre_razon_social || customer.nombre }}</p></div>
    <div class="min-h-40 flex-1 overflow-y-auto p-4"><ul v-if="cart.length" class="space-y-3"><li v-for="(item, index) in cart" :key="item.producto_id" class="rounded-xl border border-slate-200 p-3"><div class="flex justify-between gap-3"><div class="min-w-0"><p class="line-clamp-2 text-sm font-semibold text-slate-800">{{ item.nombre }}</p><p v-if="item.requiere_receta" class="mt-1 text-[11px] font-medium text-red-700">CMP: {{ item.cmp_medico || 'Pendiente' }}</p></div><button class="rounded-lg p-1 text-slate-400 hover:bg-red-50 hover:text-red-600" :aria-label="'Quitar ' + item.nombre" @click="$emit('remove', index)"><Trash2 :size="17" /></button></div><div class="mt-3 flex items-center justify-between"><div class="flex items-center rounded-lg border border-slate-200"><button class="p-1.5 text-slate-500 hover:bg-slate-50" aria-label="Reducir cantidad" @click="$emit('quantity', item, item.cantidad - 1)"><Minus :size="15" /></button><input class="w-9 border-x border-slate-200 py-1 text-center text-xs font-bold outline-none" :value="item.cantidad" min="1" type="number" @change="$emit('quantity', item, Number($event.target.value))" /><button class="p-1.5 text-slate-500 hover:bg-slate-50" aria-label="Aumentar cantidad" @click="$emit('quantity', item, item.cantidad + 1)"><Plus :size="15" /></button></div><strong class="text-sm text-slate-900">S/ {{ money(item.cantidad * item.precio_unitario) }}</strong></div></li></ul><div v-else class="grid h-full min-h-44 place-items-center text-center"><ShoppingBasket class="mb-3 text-slate-300" :size="32" /><div><p class="font-semibold text-slate-700">Tu carrito está vacío</p><p class="mt-1 text-sm text-slate-500">Selecciona productos del catálogo.</p></div></div></div>
    <footer class="border-t border-slate-100 bg-slate-50 p-4"><label class="field-label">Método de pago</label><select :value="paymentMethod" class="field-control py-2.5" @change="$emit('update:payment-method', $event.target.value)"><option value="Efectivo">Efectivo</option><option value="Yape">Yape</option><option value="Plin">Plin</option><option value="Tarjeta">Tarjeta de débito/crédito</option></select><div class="my-4 flex items-center justify-between rounded-xl bg-slate-950 p-4 text-white"><span class="text-sm font-medium">Total a pagar</span><strong class="text-2xl font-black">S/ {{ money(total) }}</strong></div><button class="btn w-full bg-emerald-600 text-white hover:bg-emerald-700" :disabled="!cart.length || processing" @click="$emit('checkout')"><LoaderCircle v-if="processing" class="animate-spin" :size="18" /><CreditCard v-else :size="18" />{{ processing ? 'Procesando venta…' : 'Completar venta' }}</button></footer>
  </aside>
</template>
<script setup>
import { CreditCard, LoaderCircle, Minus, Plus, Search, ShoppingBasket, Trash2 } from 'lucide-vue-next';
defineProps({ cart: { type: Array, default: () => [] }, customer: Object, documentNumber: { type: String, default: '' }, paymentMethod: { type: String, default: 'Efectivo' }, processing: Boolean, total: { type: Number, default: 0 } });
defineEmits(['update:document-number', 'find-customer', 'remove', 'quantity', 'update:payment-method', 'checkout']);
const money = (value) => Number(value || 0).toFixed(2);
</script>
