<template>
  <div class="space-y-6">
    <PageHeader eyebrow="Seguridad y control" title="Historial de actividad" description="Registro de operaciones realizadas por usuarios autenticados.">
      <template #actions><button class="btn btn-secondary" :disabled="loading" @click="loadLogs"><RefreshCw :size="16" :class="{ 'animate-spin': loading }" />Actualizar</button></template>
    </PageHeader>
    <div class="app-card flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><label class="text-sm font-semibold text-slate-700">Filtrar actividad</label><select v-model="action" class="field-control max-w-xs" @change="loadLogs"><option value="">Todas las acciones</option><option value="sale.created">Ventas registradas</option><option value="sale.cancelled">Ventas anuladas</option><option value="cash_register.opened">Cajas abiertas</option><option value="cash_register.closed">Cajas cerradas</option><option value="cash_register.closure_corrected">Cierres corregidos</option></select></div>
    <div v-if="error" class="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ error }}</div>
    <section class="app-card overflow-hidden"><div v-if="loading" class="grid min-h-64 place-items-center text-sm text-slate-500">Cargando actividad…</div><div v-else-if="logs.length" class="divide-y divide-slate-100"><article v-for="log in logs" :key="log.id" class="flex gap-3 p-4 sm:p-5"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl" :class="actionStyle(log.action).class"><component :is="actionStyle(log.action).icon" :size="19" /></span><div class="min-w-0 flex-1"><div class="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p class="font-bold text-slate-800">{{ actionStyle(log.action).label }}</p><time class="text-xs text-slate-500">{{ formatDate(log.created_at) }}</time></div><p class="mt-1 text-sm text-slate-600">{{ log.user?.name || 'Usuario no disponible' }}<span v-if="summary(log)" class="text-slate-500"> · {{ summary(log) }}</span></p><p v-if="log.metadata?.motivo" class="mt-1 text-sm text-slate-500">Motivo: {{ log.metadata.motivo }}</p></div></article></div><div v-else class="grid min-h-64 place-items-center p-6 text-center"><ShieldCheck :size="30" class="mb-2 text-slate-300" /><div><p class="font-semibold text-slate-700">Aún no hay actividad registrada</p><p class="mt-1 text-sm text-slate-500">Las próximas ventas y operaciones de caja aparecerán aquí.</p></div></div></section>
    <div v-if="pagination.last_page > 1" class="flex items-center justify-between"><p class="text-sm text-slate-500">Página {{ pagination.current_page }} de {{ pagination.last_page }}</p><div class="flex gap-2"><button class="btn btn-secondary" :disabled="pagination.current_page <= 1 || loading" @click="loadLogs(pagination.current_page - 1)">Anterior</button><button class="btn btn-secondary" :disabled="pagination.current_page >= pagination.last_page || loading" @click="loadLogs(pagination.current_page + 1)">Siguiente</button></div></div>
  </div>
</template>
<script setup>
import { onMounted, ref } from 'vue';
import { CircleDollarSign, RefreshCw, ShieldCheck, ShoppingBag, XCircle } from 'lucide-vue-next';
import api from '../api/axios';
import PageHeader from '../components/ui/PageHeader.vue';
const logs = ref([]), action = ref(''), loading = ref(false), error = ref(''), pagination = ref({ current_page: 1, last_page: 1 });
const styles = { 'sale.created': { label: 'Venta registrada', icon: ShoppingBag, class: 'bg-emerald-100 text-emerald-800' }, 'sale.cancelled': { label: 'Venta anulada', icon: XCircle, class: 'bg-red-100 text-red-800' }, 'cash_register.opened': { label: 'Caja abierta', icon: CircleDollarSign, class: 'bg-cyan-100 text-cyan-800' }, 'cash_register.closed': { label: 'Caja cerrada', icon: CircleDollarSign, class: 'bg-violet-100 text-violet-800' }, 'cash_register.closure_corrected': { label: 'Cierre corregido', icon: CircleDollarSign, class: 'bg-amber-100 text-amber-800' } };
const actionStyle = (value) => styles[value] || { label: value, icon: ShieldCheck, class: 'bg-slate-100 text-slate-700' };
const formatDate = (value) => new Date(value).toLocaleString('es-PE', { dateStyle: 'medium', timeStyle: 'short' });
const summary = (log) => log.metadata?.monto_corregido !== undefined ? 'Original S/ ' + Number(log.metadata.monto_original).toFixed(2) + ' → Corregido S/ ' + Number(log.metadata.monto_corregido).toFixed(2) : log.metadata?.total ? 'Total S/ ' + Number(log.metadata.total).toFixed(2) : log.metadata?.monto_inicial !== undefined ? 'Inicial S/ ' + Number(log.metadata.monto_inicial).toFixed(2) : log.metadata?.monto_final !== undefined ? 'Final S/ ' + Number(log.metadata.monto_final).toFixed(2) : '';
async function loadLogs(page = 1) { loading.value = true; error.value = ''; try { const { data } = await api.get('/actividad', { params: { page, action: action.value || undefined } }); logs.value = data.data || []; pagination.value = { current_page: data.current_page || 1, last_page: data.last_page || 1 }; } catch { error.value = 'No se pudo cargar la actividad. Inténtalo nuevamente.'; } finally { loading.value = false; } }
onMounted(loadLogs);
</script>