<template>
  <div class="mx-auto max-w-7xl space-y-6">
    <PageHeader eyebrow="Relación comercial" title="Clientes" description="Consulta el historial de compras y mantiene los datos de contacto actualizados.">
      <template #actions><button class="btn btn-primary" @click="openEditor()">Nuevo cliente</button></template>
    </PageHeader>
    <InlineNotice :notice="notice" @dismiss="notice = null" />

    <div class="grid gap-4 sm:grid-cols-3"><article class="app-card p-5"><p class="text-sm font-semibold text-slate-500">Clientes registrados</p><p class="mt-2 text-3xl font-black text-cyan-700">{{ total }}</p></article><article class="app-card p-5"><p class="text-sm font-semibold text-slate-500">Clientes recurrentes</p><p class="mt-2 text-3xl font-black text-violet-700">{{ repeatCustomers }}</p><p class="mt-1 text-xs text-slate-500">Dos o más compras completadas.</p></article><article class="app-card p-5"><p class="text-sm font-semibold text-slate-500">Compra promedio visible</p><p class="mt-2 text-3xl font-black text-emerald-700">S/ {{ money(averageSpend) }}</p><p class="mt-1 text-xs text-slate-500">En los resultados cargados.</p></article></div>

    <section class="app-card overflow-hidden"><div class="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-slate-900">Base de clientes</h2><p class="text-sm text-slate-500">Busca por nombre, DNI/RUC o teléfono.</p></div><input v-model="search" class="field-control sm:max-w-sm" placeholder="Buscar cliente" @input="debouncedLoad" /></div>
      <div v-if="loading" class="grid min-h-64 place-items-center text-sm text-slate-500">Cargando clientes…</div>
      <div v-else-if="customers.length" class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="p-4">Cliente</th><th class="p-4">Documento</th><th class="p-4">Contacto</th><th class="p-4 text-center">Compras</th><th class="p-4 text-right">Acumulado</th><th class="p-4 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="customer in customers" :key="customer.id" class="hover:bg-slate-50/70"><td class="p-4"><p class="font-bold text-slate-800">{{ customer.nombre_razon_social }}</p><p class="text-xs text-slate-500">{{ customer.direccion || 'Sin dirección registrada' }}</p></td><td class="p-4"><span class="font-mono text-xs text-slate-600">{{ customer.tipo_documento }} · {{ customer.numero_documento }}</span></td><td class="p-4"><p>{{ customer.telefono || '—' }}</p><p class="text-xs text-slate-500">{{ customer.email || '—' }}</p></td><td class="p-4 text-center font-bold text-slate-800">{{ customer.compras_completadas || 0 }}</td><td class="p-4 text-right font-black text-emerald-700">S/ {{ money(customer.gasto_total) }}</td><td class="p-4"><div class="flex justify-end gap-2"><button class="btn btn-secondary !px-3 !py-2 text-xs" @click="openProfile(customer)">Perfil</button><button class="btn btn-secondary !px-3 !py-2 text-xs" @click="openEditor(customer)">Editar</button></div></td></tr></tbody></table></div><div v-else class="grid min-h-64 place-items-center text-sm text-slate-500">No se encontraron clientes.</div>
      <div v-if="lastPage > 1" class="flex items-center justify-between border-t border-slate-100 p-4"><span class="text-sm text-slate-500">Página {{ page }} de {{ lastPage }}</span><div class="flex gap-2"><button class="btn btn-secondary" :disabled="page <= 1" @click="loadCustomers(page - 1)">Anterior</button><button class="btn btn-secondary" :disabled="page >= lastPage" @click="loadCustomers(page + 1)">Siguiente</button></div></div>
    </section>

    <div v-if="profile" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm"><div class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><header class="flex items-center justify-between bg-slate-950 p-5 text-white"><div><p class="text-xs font-semibold uppercase tracking-wider text-cyan-300">Perfil comercial</p><h2 class="font-bold">{{ profile.cliente.nombre_razon_social }}</h2></div><button class="text-slate-300 hover:text-white" @click="profile = null">✕</button></header><div class="space-y-5 p-5"><div class="grid gap-3 sm:grid-cols-4"><Metric label="Compras" :value="profile.metricas.compras_completadas" /><Metric label="Acumulado" :value="'S/ ' + money(profile.metricas.gasto_total)" /><Metric label="Ticket promedio" :value="'S/ ' + money(profile.metricas.ticket_promedio)" /><Metric label="Última compra" :value="formatDate(profile.metricas.ultima_compra)" /></div><div><h3 class="font-bold text-slate-900">Historial de compras</h3><div v-if="profile.ventas.length" class="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-100"><article v-for="sale in profile.ventas" :key="sale.id" class="flex items-center justify-between p-4"><div><p class="font-bold text-slate-800">Venta #{{ sale.id }}</p><p class="text-xs text-slate-500">{{ formatDate(sale.created_at) }} · {{ sale.metodo_pago }}</p></div><strong class="text-emerald-700">S/ {{ money(sale.total) }}</strong></article></div><p v-else class="mt-3 text-sm text-slate-500">No hay compras completadas para este cliente.</p></div></div></div></div>

    <div v-if="editorOpen" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm"><form class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" @submit.prevent="saveCustomer"><h2 class="text-lg font-bold text-slate-900">{{ form.id ? 'Editar cliente' : 'Nuevo cliente' }}</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><label><span class="field-label">Documento</span><select v-model="form.tipo_documento" class="field-control"><option>DNI</option><option>RUC</option><option>CE</option></select></label><label><span class="field-label">Número</span><input v-model.trim="form.numero_documento" class="field-control" required /></label><label class="sm:col-span-2"><span class="field-label">Nombre o razón social</span><input v-model.trim="form.nombre_razon_social" class="field-control" required /></label><label><span class="field-label">Teléfono</span><input v-model.trim="form.telefono" class="field-control" maxlength="15" /></label><label><span class="field-label">Correo</span><input v-model.trim="form.email" class="field-control" type="email" /></label><label class="sm:col-span-2"><span class="field-label">Dirección</span><input v-model.trim="form.direccion" class="field-control" /></label></div><div class="mt-6 flex justify-end gap-3"><button class="btn btn-secondary" type="button" @click="editorOpen = false">Cancelar</button><button class="btn btn-primary" :disabled="saving">{{ saving ? 'Guardando…' : 'Guardar' }}</button></div></form></div>
  </div>
</template>
<script setup>
import { computed, defineComponent, h, onMounted, ref } from 'vue';
import api from '../api/axios';
import InlineNotice from '../components/ui/InlineNotice.vue';
import PageHeader from '../components/ui/PageHeader.vue';
const Metric = defineComponent({ props: { label: String, value: [String, Number] }, setup(props) { return () => h('div', { class: 'rounded-xl bg-slate-50 p-3' }, [h('p', { class: 'text-xs font-semibold text-slate-500' }, props.label), h('p', { class: 'mt-1 text-sm font-black text-slate-900' }, String(props.value || '—'))]); } });
const customers = ref([]), profile = ref(null), loading = ref(false), saving = ref(false), search = ref(''), page = ref(1), lastPage = ref(1), total = ref(0), notice = ref(null), editorOpen = ref(false);
const empty = () => ({ id: null, tipo_documento: 'DNI', numero_documento: '', nombre_razon_social: '', telefono: '', email: '', direccion: '' });
const form = ref(empty()); let timer;
const money = value => Number(value || 0).toFixed(2); const formatDate = value => value ? new Date(value).toLocaleString('es-PE', { dateStyle: 'medium' }) : '—';
const repeatCustomers = computed(() => customers.value.filter(customer => Number(customer.compras_completadas) >= 2).length);
const averageSpend = computed(() => customers.value.length ? customers.value.reduce((sum, customer) => sum + Number(customer.gasto_total || 0), 0) / customers.value.length : 0);
function show(message, type = 'success') { notice.value = { message, type }; }
function debouncedLoad() { clearTimeout(timer); timer = setTimeout(() => loadCustomers(1), 250); }
async function loadCustomers(targetPage = 1) { loading.value = true; try { const { data } = await api.get('/clientes', { params: { q: search.value || undefined, page: targetPage } }); customers.value = data.data || []; page.value = data.current_page || 1; lastPage.value = data.last_page || 1; total.value = data.total || customers.value.length; } catch { show('No se pudo cargar la base de clientes.', 'error'); } finally { loading.value = false; } }
async function openProfile(customer) { try { const { data } = await api.get('/clientes/' + customer.id + '/resumen'); profile.value = data; } catch { show('No se pudo abrir el perfil del cliente.', 'error'); } }
function openEditor(customer = null) { form.value = customer ? { ...empty(), ...customer } : empty(); editorOpen.value = true; }
async function saveCustomer() { saving.value = true; try { const payload = { ...form.value, telefono: form.value.telefono || null, email: form.value.email || null, direccion: form.value.direccion || null }; if (form.value.id) await api.put('/clientes/' + form.value.id, payload); else await api.post('/clientes', payload); editorOpen.value = false; show('Datos del cliente guardados.'); await loadCustomers(page.value); } catch (error) { show(error.response?.data?.message || 'No se pudo guardar el cliente.', 'error'); } finally { saving.value = false; } }
onMounted(loadCustomers);
</script>